### ISSUE TITLE
WebCatalog 38.0.3 Failed to Connect to Server ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by MacTerrassa** [quanglam2807/webcatalog#1546]
Hello, I have been testing all your applications for weeks on an iMac Intel Core 2 Duo (2007) with Mac OS X 10.11 El Capitan.

Many of them give me random problems in the update search function: when I ask for it manually, many times it responds that it is not connected to the internet, when it is.

Other times, both manually and automatically, it makes the query and offers to update correctly.
 
Today it happened to me again with almost all its applications, and WebCatalog does not show me the page of apps to install, and since I also had a problem with the playback from the Spotify app installed with WebCatalag and could not find updates, I decided to delete all the WebCatalog applications and their folders from the user library (with a search by name with EasyFind of everything related to WebCatalog or its applications).

But now it remains the same: the program does not show content on the home page or applications to install. I send a screenshot of that page with the development tools displayed in the network tab.

From what I understand about it, there is some problem with the loading of some components due to a failure in the certificates. It can be fixed? Is it my configuration or a general failure of your website or applications?

I do not know if it will be a solution, but later I will try to try with a previous version, in case the problem is with the version I use, the last one obtained on your website: 8.0.3.

Regards
![screenshot_28](https://user-images.githubusercontent.com/27101198/138487010-61c165d7-02fb-4470-b26f-959b2c770384.png)

**Comment by quanglam2807** [comment]
This happens because macOS 10.11 is no longer updated and doesn't have the latest web certificates. 

The good new is that you can install the needed component/certificate manually.

1. Download the certificate from https://letsencrypt.org/certs/isrgrootx1.der
2. Open "Keychain Access", click "System" on the sidebar, then drag the downloaded file into the window to install it.
3. Find "ISRG Root X1" in the list and double click it. There'll be a Trust menu you can open, and then change "Use System Defaults" to "Always Trust". Then close the pop up window and it should ask you to enter your password.

You can read more about this problem here: https://community.letsencrypt.org/t/certificates-are-not-trusted-on-chrome-and-safari-on-old-imac-with-el-capitan/161231/4

**Comment by MacTerrassa** [comment]
Thanks your answer really fixes the problem. And also the program accepts the update check requests now, which I suppose would also block the problem with the certificate.

Thank you very much, I also have problems with other programs and I had not considered that perhaps this of the certificates will require renewal more often. And other so-called security improvements, which are rather reasons to declare working machines obsolete. But hey, the main thing my problem with your program is solved like this, at least until the next time :-) Thank you very much. 

Regards
