### ISSUE TITLE
bug: Unable to Play Udemy Videos using Udemy Webapp

### ISSUE THREAD

**Issue by Bishal-Mahanta** [quanglam2807/webcatalog#1567]
Specifications:

WebCatalog Version: 40.1.0 (x64)
OS : Manjaro Linux x86_64, 5.13.19-2-MANJARO, GNOME 40.5
Description:
[OPEN] Udemy Webapp installed on your computer using Webcatalog.
[CLICK] Play any video from Udemy.

Udemy Opened from Webcatalog
![Screenshot from 2021-11-18 10-41-22](https://user-images.githubusercontent.com/64310226/142355896-5b419892-840d-444e-ae9e-2d418c0072f3.png)

Udemy Opened from Browser
![Screenshot from 2021-11-18 10-41-59](https://user-images.githubusercontent.com/64310226/142355961-f6145aed-805f-4f0e-8d0b-a2a3f03312b9.png)

Steps to Reproduce:
Download WebCatalog-40.1.0.AppImage for x64 linux from the official website, run on Manjaro Linux x86_64

**Comment by quanglam2807** [comment]
Have you tried to update the Udemy app to v21.0.1, @Bishal-Mahanta?

**Comment by Bishal-Mahanta** [comment]
> Have you tried to update the Udemy app to v21.0.1, @Bishal-Mahanta?

Yup I always keep updated

**Comment by quanglam2807** [comment]
This happens because currently, WebCatalog doesn't support WidevineDRM technology on Windows. We'll try to add support for it in the future.

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
