### ISSUE TITLE
feature: Ability to keep application running after quitting (agent)

### ISSUE THREAD

**Issue by aubreypwd** [quanglam2807/webcatalog#1623]
# Feature Request
**Specifications:**
- WebCatalog Version: 
![image](https://user-images.githubusercontent.com/1753298/151482804-2924f184-89e1-4f43-ac6d-a54bb468250f.png)
- Neutron Version: 
- OS (macOS, Windows, Linux): macOS

**Description:**

Basically I want to quit an app, like Facebook, and when I quit the app it (icon) leaves my dock as if it quit. But it's still active (an agent?) and able to receive and push notifications to notification center, if that is at all possible.

**Comment by quanglam2807** [comment]
Thanks for the feedback, @aubreypwd. Currently, this is not possible because WebCatalog doesn't support Web Push API: https://developer.mozilla.org/en-US/docs/Web/API/Push_API (Electron doesn't support it). We'll try to work on this in the future if possible.

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/,
